In [2]:
#exo1
from array import*
array_num= array('i',[1,4,3,2,5,7,9,3])
num_list=array_num.tolist()
print("la liste converti:",num_list)

la liste converti: [1, 4, 3, 2, 5, 7, 9, 3]


In [6]:
#exo2
import numpy as np
t=np.arange(16).reshape(4,4)
result=np.trace(t)
print("la somme des elements diagonaux est:",result)

la somme des elements diagonaux est: 30


In [12]:
#exo3
import numpy as np
x=np.array([[1,2],[3,5]])
print("les valeurs supperieur a 2 sont",x[x>2])


les valeurs supperieur a 2 sont [3 5]


In [13]:
#exo4
import numpy as np
a=np.array([[2,3],[5,6]],dtype=np.float64)
b=np.array([[7,8],[1,4]],dtype=np.float64)
C=np.add(a,b)
print(C)

[[ 9. 11.]
 [ 6. 10.]]


In [14]:
#exo5
import numpy as np
a=np.random.rand(3,4)
print(a)
b=a-a.mean(axis=1, keepdims=True)
print(b)

[[0.66108694 0.80666019 0.35837018 0.29239167]
 [0.22028567 0.76370509 0.88714543 0.73168642]
 [0.58603158 0.49468983 0.32366282 0.46514539]]
[[ 0.1314597   0.27703294 -0.17125706 -0.23723557]
 [-0.43041998  0.11299944  0.23643977  0.08098077]
 [ 0.11864917  0.02730743 -0.14371958 -0.00223701]]
